import Cards from "./Cards";

let deck: Cards[] = [
    {name: "Ace of Spades", image: "/pictures/pa.webp", value: 1},
    {name: "Two of Spades", image: "/pictures/p2.webp", value: 2},
    {name: "Three of Spades", image: "/pictures/p3.webp", value: 3},
    {name: "Four of Spades", image: "/pictures/p4.webp", value: 4},
    {name: "Five of Spades", image: "/pictures/p5.webp", value: 5},
    {name: "Six of Spades", image: "/pictures/p6.webp", value: 6},
    {name: "Seven of Spades", image: "/pictures/p7.webp", value: 7},
    {name: "Eight of Spades", image: "/pictures/p8.webp", value: 8},
    {name: "Nine of Spades", image: "/pictures/p9.webp", value: 9},
    {name: "Ten of Spades", image: "/pictures/p10.webp", value: 10},
    {name: "Jack of Spades", image: "/pictures/pj.webp", value: 10},
    {name: "Queen of Spades", image: "/pictures/pq.webp", value: 10},
    {name: "King of Spades", image: "/pictures/pk.webp", value: 10},
    {name: "Ace of Clubs", image: "/pictures/ka.webp", value: 1},
    {name: "Two of Clubs", image: "/pictures/k2.webp", value: 2},
    {name: "Three of Clubs", image: "/pictures/k3.webp", value: 3},
    {name: "Four of Clubs", image: "/pictures/k4.webp", value: 4},
    {name: "Five of Clubs", image: "/pictures/k5.webp", value: 5},
    {name: "Six of Clubs", image: "/pictures/k6.webp", value: 6},
    {name: "Seven of Clubs", image: "/pictures/k7.webp", value: 7},
    {name: "Eight of Clubs", image: "/pictures/k8.webp", value: 8},
    {name: "Nine of Clubs", image: "/pictures/k9.webp", value: 9},
    {name: "Ten of Clubs", image: "/pictures/k10.webp", value: 10},
    {name: "Jack of Clubs", image: "/pictures/kj.webp", value: 10},
    {name: "Queen of Clubs", image: "/pictures/kq.webp", value: 10},
    {name: "King of Clubs", image: "/pictures/kk.webp", value: 10},
    {name: "Ace of Hearts", image: "/pictures/sa.webp", value: 1},
    {name: "Two of Hearts", image: "/pictures/s2.webp", value: 2},
    {name: "Three of Hearts", image: "/pictures/s3.webp", value: 3},
    {name: "Four of Hearts", image: "/pictures/s4.webp", value: 4},
    {name: "Five of Hearts", image: "/pictures/s5.webp", value: 5},
    {name: "Six of Hearts", image: "/pictures/s6.webp", value: 6},
    {name: "Seven of Hearts", image: "/pictures/s7.webp", value: 7},
    {name: "Eight of Hearts", image: "/pictures/s8.webp", value: 8},
    {name: "Nine of Hearts", image: "/pictures/s9.webp", value: 9},
    {name: "Ten of Hearts", image: "/pictures/s10.webp", value: 10},
    {name: "Jack of Hearts", image: "/pictures/sj.webp", value: 10},
    {name: "Queen of Hearts", image: "/pictures/sq.webp", value: 10},
    {name: "King of Hearts", image: "/pictures/sk.webp", value: 10},
    {name: "Ace of Diamonds", image: "/pictures/la.webp", value: 1},
    {name: "Two of Diamonds", image: "/pictures/l2.webp", value: 2},
    {name: "Three of Diamonds", image: "/pictures/l3.webp", value: 3},
    {name: "Four of Diamonds", image: "/pictures/l4.webp", value: 4},
    {name: "Five of Diamonds", image: "/pictures/l5.webp", value: 5},
    {name: "Six of Diamonds", image: "/pictures/l6.webp", value: 6},
    {name: "Seven of Diamonds", image: "/pictures/l7.webp", value: 7},
    {name: "Eight of Diamonds", image: "/pictures/l8.webp", value: 8},
    {name: "Nine of Diamonds", image: "/pictures/l9.webp", value: 9},
    {name: "Ten of Diamonds", image: "/pictures/l10.webp", value: 10},
    {name: "Jack of Diamonds", image: "/pictures/lj.webp", value: 10},
    {name: "Queen of Diamonds", image: "/pictures/lq.webp", value: 10},
    {name: "King of Diamonds", image: "/pictures/lk.webp", value: 10},
];
export default deck;
